services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173    
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent rebuilds
    command: npm run dev
